name: Validacion Estricta - Backend

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

jobs:
  test-backend:
    runs-on: ubuntu-latest

    # 1. Levantamos una base de datos PostgreSQL efímera para las pruebas
    services:
      postgres:
        image: postgres:15-alpine
        env:
          POSTGRES_USER: admin
          POSTGRES_PASSWORD: adminpassword
          POSTGRES_DB: alabanza_db_test
        ports:
          - 5432:5432
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5

    # 2. Le indicamos a GitHub que ejecute los comandos dentro de la carpeta backend
    defaults:
      run:
        working-directory: ./backend

    steps:
      - name: 📥 Clonar el código
        uses: actions/checkout@v4

      - name: 🟢 Configurar Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "20"

      - name: 📦 Instalar dependencias
        run: npm ci

      - name: 🗄️ Estructurar Base de Datos de Prueba
        env:
          PGPASSWORD: adminpassword
        # Usamos el usuario 'admin' y la BD 'alabanza_db_test' que ya creó Docker
        run: |
          sudo apt-get install -y postgresql-client
          psql -h localhost -U admin -d alabanza_db_test -f ${{ github.workspace }}/database/init.sql

      - name: 🧪 Ejecutar Pruebas y Validar Cobertura (>80%)
        env:
          DATABASE_URL: postgresql://admin:adminpassword@localhost:5432/alabanza_db_test
          JWT_SECRET: super_secreto_alabanza_2026_desarrollo
          NODE_ENV: test
        run: npm run test:coverage
